### ISSUE TITLE
Create Utility documentation page template

### ISSUE THREAD

**Issue by sarinapadilla** [NCIOCPL/ncids#1593]
## As a developer, I want a template that builts a Utility page based on entered information, so that I can easily build Utility pages.

The YAML in the [comment](https://github.com/NCIOCPL/ncids/issues/1593#issuecomment-1989478173) below has the template setup!

Some notes:
* The `is_responsive_enabled` display of "Yes" will link to the section about responsive modifiers on the overview Utilities page.
* The `active_state_modifiers` will each link to their corresponding section on the overview Utilities page.

> **ESTIMATE** TBD

### Resources:
* [Mural board](https://app.mural.co/t/publicissapient7269/m/publicissapient7269/1708713324713/8c29da52a2d2584c52555e5439d99047355482e2?sender=uc0870c1f8489401535da0005) with the final comp for page
* [Utilities spreadsheet](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLNewCgovUXDesignSystem/Shared%20Documents/General/Details%20-%20Release%202/R2.4/Development%20and%20Testing/USWDS_Utilities.xlsx?d=waeac153a696a4419941b142cc9b627f1&csf=1&web=1&e=8THgYK) (not sure if we need this for the template but included just in case)

### Acceptance Criteria
```gherkin
Scenario: [title]
  Given [context]
    And [some more context]
  When  [event]
  Then  [outcome]
    And [another outcome]
```

**Comment by bryanpizzillo** [comment]
```

browser_title: string
page_title: string
nav_label: string
nav_order: number
template_type: utility

intro: string

utility_modules:
  - name: string
    ## This is the 
    uswds_utility_module_name: string
    description: string
    mixins_and_functions:
      - functions come from core/functions/utility folder
    utility_class_info:
      gzip_size: string
      uncompressed_size: string
      state_modifiers: [ 'active', 'hover', 'focus', 'visited', 'none' ]
      is_responsive_enabled: boolean
      ## The following could be something like bg-color-[color] or font-[family]-[size]
      ## should the [x] be a link to the token listing for the thing?
      class_naming: ???
      class_display_component: string
      classes:
        # The structure of this depends on the class_display_component type
        # however, the class_name is required for all. We might be able to
        # enforce this in the schema with some trickery.
        - class_name: string
          ...
        - ...
      example_usage:
        - heading: string
          code: string
      
---

This is the markdown for the tokens portion of the page.
```
