### ISSUE TITLE
Regression images differ local vs workflow

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#1647]
Regressions fail locally when using background icons. Regressions are not failing in the workflow. This has been tested on Intel and M2 (M1 is still hanging while running locally).

---

Locally, when running regression tests:
<img width="598" alt="Screenshot 2024-04-11 at 11 48 47 AM" src="https://github.com/NCIOCPL/ncids/assets/85901679/a914beb5-316b-4b18-adb2-ff27cea6d81e">

```scss
// Storybook CSS on develop:
ul.nci-cta-strip li .usa-button::after {
    display: inline-block;
    height: 2ex;
    width: 2ex;
    background: none;
    background-color: currentColor;
    -webkit-mask: url(static/media/navigate_next.84649ddd.svg) no-repeat center / contain;
    mask: url(static/media/navigate_next.84649ddd.svg) no-repeat center / contain;
    content: "";
    vertical-align: top;
    margin-left: 1px;
```

```scss
// Storybook css on localhost:
ul.nci-cta-strip li .usa-button::after {
    display: inline-block;
    height: 2ex;
    width: 2ex;
    background: none;
    background-color: currentColor;
    mask: url(static/media/_/_/packages/ncids-css/uswds-img/usa-icons/navigate_next.svg) no-repeat center / contain;
    content: "";
    vertical-align: top;
    margin-left: 1px;
}
```
