### ISSUE TITLE
NICDS Icons SCSS partials 

### ISSUE THREAD

**Issue by karlikpj** [NCIOCPL/ncids#198]
We need to create the scss for the font awesome icons and include the font files in our packages for development.

We need to create the icon component that will consume the scss and be used in our design system. this component will be a div wrapper with the necessary a11y attributes that match the uswds icons.

By default:

We will use the "solid" variant of the free Font Awesome v5 set (https://fontawesome.com/v5.15/icons?d=gallery&p=1&s=solid&m=free) as this is the only one with all icons required for the site (search/ui carrots) 

We will also use the "brand" variant (https://fontawesome.com/v5.15/icons?d=gallery&p=1&s=brands&m=free) for the social media icons for co branding.

### create ncids-icons.scss that will include
* font awesome font family imports
* font awesome font face decelerations
* base icon style & size variant *based on the USWDS size variants.  (https://designsystem.digital.gov/components/icon/)
* class names / unicode content for each icon 

_sizing from uswds.css_  
```css
.usa-icon{
  height:1em;
  width:1em;
}

.usa-icon--size-3{
  height:1.5rem;
  width:1.5rem;
}

.usa-icon--size-4{
  height:2rem;
  width:2rem;
}

.usa-icon--size-5{
  height:2.5rem;
  width:2.5rem;
}

.usa-icon--size-6{
  height:3rem;
  width:3rem;
}

.usa-icon--size-7{
  height:3.5rem;
  width:3.5rem;
}

.usa-icon--size-8{
  height:4rem;
  width:4rem;
}

.usa-icon--size-9{
  height:4.5rem;
  width:4.5rem;
}
```

### create react component
* icon component that displays icon based on prop-type
* prop for the use of the size variant

_example with required attributes for a11y_
```js
<div class="ncids-icon" aria-hidden="true" focusable="false" role="img">
```

> **ESTIMATE** TBD

### Acceptance Criteria
*As a user I am able to see the chosen icon to display on screen.
*As a user I am able to set the size of the icon (variant 3 to 9)
*As a user I am able control the color of the icons.

### Resources:
* https://fontawesome.com/v5.15/icons?d=gallery&p=2&m=free (free icon set & icon names)

### Notes

*This ticket is required for search in header / social media in footer
