### ISSUE TITLE
`usa-section--dark` link colors

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#781]
### Issue description
`.usa-section--dark` changes all link colors to `$theme-link-reverse-color`. This also changes the text color on all anchor links themed as buttons (`a.usa-button`). The dark section variant should not override set button colors. 

This causes accessibility issues when `$theme-link-reverse-color` is used with certain button background colors.  

> **ESTIMATE** TBD

```scss
// _usa-section.scss

.usa-section--dark {
  background-color: color("primary-darker");
  color: color($theme-text-reverse-color);

  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    // TODO: This should use a theme-able color,
    // and should probably default to white
    color: color("accent-cool");
  }

  p {
    color: color($theme-text-reverse-color);
  }

  a {
    color: color($theme-link-reverse-color);

    &:hover {
      color: color($theme-link-reverse-hover-color);
    }

    &:active {
      color: color($theme-link-reverse-active-color);
    }
  }
}
```

## Dev notes
After discussion, we decided that the best solution for our current needs would be to update our copied version of `usa-section.scss` to:

```scss
  a:not(.usa-button) {
    color: color($theme-link-reverse-color);

```
