### ISSUE TITLE
Enabler: Allow regression tests for print styles

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#929]
## Allow regression tests for print styles

Several components use `@media print` styles for printed content. We should add regression checks for components that use CSS to change styles for print. 

For example:

```scss
.usa-radio__input {
  &:checked {
    @include format-input {
      @media print {
        box-shadow: inset 0 0 0 units($theme-input-select-border-width)
            color("white"),
          inset 0 0 0 units(2) color("primary"),
          0 0 0 units($theme-input-select-border-width) color("primary");
      }
    }
  }
}
```

```scss
@media print {
   @include u-display('none');
}
```

### Subtasks
- [ ] Add regressions for all components that utilize print media queries 

### Related
* #921

### Notes

The chrome engine seems to have a flag  `--enable-print-browser` that can be passed as an argument to the config - this may not work the same for Playwright. As with 921,  if this is the solution, this flag should only be passed for the stories that need them, not globally.
