### ISSUE TITLE
Improve BS generate image workflow

### ISSUE THREAD

**Issue by olitharp-nci** [NCIOCPL/ncids#983]
Generate bs image workflow can exit with unhelpful messages:

```bash
Browser Console Log 0: BackstopTools have been installed. 
SCENAerror Command failed with exit code 1.
```

---

Bryan said do this:

```yml
      ## Now generate the reference images
      - name: Run image generation
        working-directory: ./testing/ncids-css-testing
        run: node_modules/.bin/backstop reference --config='backstop.config.js' --docker
```

This will remove yarn from the workflow to make sure that warnings and errors are being correctly outputted.
